use_frameworks!

platform :ios, '9.0'

target 'JDNetwork_Example' do
  pod 'JDNetwork', :path => '../'

  target 'JDNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
